Remove Godeps; vendor deps in diego-release
[#78292566]

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -3,25 +3,38 @@
 
 set -e -x
 
-export GOPATH=$PWD/Godeps/_workspace:$GOPATH
+go get -t -v ./...
 
-FIRST_GOPATH=`echo $GOPATH | cut -d':' -f1`
-
-mkdir -p $FIRST_GOPATH/bin
-export PATH=$FIRST_GOPATH/bin:$PATH
-
-# lock down etcd to SHA in diego-release/src/etcd
-# since latest code is very broken
-# See: https://github.com/coreos/etcd/issues/986
-go get -u github.com/coreos/etcd
-pushd ${FIRST_GOPATH}/src/github.com/coreos/etcd
-git checkout 0a2384bf4daec35a814244dc4d885e14f18b5ef1
+## Lock down etcd since latest code is very broken
+## See: https://github.com/coreos/etcd/issues/986
+export first_gospace=$(echo $GOPATH | cut -d ':' -f 1)
+mkdir -p $first_gospace/src/github.com/coreos/etcd
+pushd $first_gospace/src/github.com/coreos/etcd
+  git clone https://github.com/coreos/etcd.git . || true
+  git checkout 0a2384bf4daec35a814244dc4d885e14f18b5ef1
+  go install .
 popd
-go install github.com/coreos/etcd
 
-go get -u github.com/apcera/gnatsd
+go get github.com/apcera/gnatsd
 go get github.com/dustin/goveralls
 go get code.google.com/p/go.tools/cmd/cover
 go install github.com/onsi/ginkgo/ginkgo
 
+for gospace in $(echo $GOPATH | tr ':' ' '); do
+  export PATH=$gospace/bin:$PATH
+done
+
 ginkgo -cover -r -failOnPending -randomizeAllSpecs -race "$@"
+
+# don't leak coveralls token
+set +x
+
+if [ -n "$COVERALLS_TOKEN" ]; then
+  profiles=$(find . -name '*.coverprofile' | grep -v fake | grep -v Godeps | grep -v integration.coverprofile)
+
+  echo mode: set > all.coverprofile
+  cat $profiles | grep -v mode: >> all.coverprofile
+
+  goveralls -service drone.io -coverprofile=all.coverprofile $COVERALLS_TOKEN || \
+    echo "Coveralls failed. :("
+fi
